### ISSUE TITLE
Comments: View, Submit, Delete, Vote

### ISSUE THREAD

**Issue by jschr** [KristerV/heliumpay-budgetweb-backend#24]
## Overview
Users will need to able to comment on proposals proposals and vote on other users comments. They will also need to edit and delete their own comments. The proposed feature set is using [dash central](https://www.dashcentral.org/budget) as a guideline. 

## API
```yml
GET   /comments?proposalHash= -> get comments for proposal # must provide a proposal
POST  /comments               -> new comment
        {text, proposalId, replyToId}
PUT   /comments/:id           -> update comment
        {text}
POST  /comments/:id/vote      -> new vote count
        {direction: -1 | 0 | 1}
DEL   /comments/:id           -> delete comment
```

## Schema
```yml
comment
  id: pk
  userId: fk -> user.id # owner
  replyToId: fk -> comment.id # if set, is a reply
  text: string

comment_vote
  id: pk, fk -> comment.id
  userId: pk, fk -> user.id
  dir: int
```

## References
* https://stackoverflow.com/questions/8112831/implementing-comments-and-likes-in-database
* https://stackoverflow.com/questions/192220/what-is-the-most-efficient-elegant-way-to-parse-a-flat-table-into-a-tree/192462#192462
* https://www.reddit.com/dev/api/#POST_api_vote
